trigger: none

pool: Latest-Pool

stages:
  - stage: InitValidatePlan
    displayName: InitValidatePlan
    jobs:
      - job: InitValidatePlanJob
        displayName: InitValidatePlanJob
        steps:
          
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'rumuitserviceconnection'
              backendAzureRmStorageAccountName: 'test42022'
              backendAzureRmContainerName: 'bawla-container'
              backendAzureRmKey: 'terraform.tfstate'

  # - stage: securityScan
  # - stage: ApprovalAndApply
